name: 'Setup Project'
description: 'Setup project with pnpm, Node.js, and dependencies'

runs:
  using: composite
  steps:
    - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
      with:
        install: false

    - name: Use Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: '.tool-versions'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
