name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: ./.github/actions/setup-project

      - name: Lint JS
        run: pnpm lint:js

      - name: Lint Style
        run: pnpm lint:style
