name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: ./.github/actions/setup-project

      - run: pnpm lint:js

  lint-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: ./.github/actions/setup-project

      - run: pnpm lint:style

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: ./.github/actions/setup-project

      - run: pnpm test

  ci:
    if: ${{ always() }}
    needs: [lint-js, lint-style, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        run: |
          test "${{ needs.lint-js.result }}" = "success"
          test "${{ needs.lint-style.result }}" = "success"
          test "${{ needs.test.result }}" = "success"
